# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anticipate < Formula
  desc "Anticipate CLI"
  homepage ""
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.2.0/anticipate_Darwin_x86_64.tar.gz"
      sha256 "ad820a83ce52640c3a396911fa5b9f36545f595b217a1827e065e3fce8e24f33"

      def install
        bin.install "anticipate"
      end
    end
    on_arm do
      url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.2.0/anticipate_Darwin_arm64.tar.gz"
      sha256 "a46fee6b81084919723c8cda983834acd4ff9f4f63e904bca312c16917be1537"

      def install
        bin.install "anticipate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.2.0/anticipate_Linux_x86_64.tar.gz"
        sha256 "dfe573994affdac843dde7bfee6de9bbe9399896f202837c7ee9d7f8b09b59ac"

        def install
          bin.install "anticipate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.2.0/anticipate_Linux_arm64.tar.gz"
        sha256 "910738c913e71e091ecd833a4395b6a0bb061bb724b7d9f9ac793ee1c53ecf25"

        def install
          bin.install "anticipate"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anticipate version")
  end
end
