# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anticipate < Formula
  desc "Anticipate CLI"
  homepage ""
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.0.5/anticipate_Darwin_x86_64.tar.gz"
      sha256 "2768b5ffc1594660a1ce6c382ee1b9413ad2a6f6e51a129c444f2de715fd92df"

      def install
        bin.install "anticipate"
      end
    end
    on_arm do
      url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.0.5/anticipate_Darwin_arm64.tar.gz"
      sha256 "6c4d5268d232e2df7b60df93828990d1e859ab3d213478dc832c5f9e0288a16d"

      def install
        bin.install "anticipate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.0.5/anticipate_Linux_x86_64.tar.gz"
        sha256 "09752297df4621e3f51c7bc9fccb7cbfe8d3915f32c808b14a75f23d40eed072"

        def install
          bin.install "anticipate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ResoluteError/Anticipate-CLI/releases/download/v0.0.5/anticipate_Linux_arm64.tar.gz"
        sha256 "46ed32947589090f30984d8a8eb52876e03c1fe67da0c64224a96b01cfccdec4"

        def install
          bin.install "anticipate"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anticipate version")
  end
end
