# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anticipate < Formula
  desc "Anticipate CLI"
  homepage ""
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ResoluteError/Go-CLI-Showcase/releases/download/v0.0.3/Go-CLI-Showcase_Darwin_x86_64.tar.gz"
      sha256 "29d45632c7ca63da65fb7991f3822cf97ef7dadf34ba6def45c5ec399edff506"

      def install
        bin.install "anticipate"
      end
    end
    on_arm do
      url "https://github.com/ResoluteError/Go-CLI-Showcase/releases/download/v0.0.3/Go-CLI-Showcase_Darwin_arm64.tar.gz"
      sha256 "a98f25e1dd6aaef96c6c1c3dd82a8a5fb6e0bdc68f3794e51821dde7fec64c8d"

      def install
        bin.install "anticipate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ResoluteError/Go-CLI-Showcase/releases/download/v0.0.3/Go-CLI-Showcase_Linux_x86_64.tar.gz"
        sha256 "b0e365bef54fec8832508bd9ea2194eb0a6e07d8bd6af645eb8e235dd5bc791c"

        def install
          bin.install "anticipate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ResoluteError/Go-CLI-Showcase/releases/download/v0.0.3/Go-CLI-Showcase_Linux_arm64.tar.gz"
        sha256 "6ee8afab2fd247788ed655192af027842a40fa3416a57b8c3a1e47e898a38866"

        def install
          bin.install "anticipate"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anticipate version")
  end
end
